name: Deploy to Production

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to BeGet server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: psponline.beget.tech
          username: psponline_monkey
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/p/psponline/psponline.beget.tech/public_html
            bash deploy.sh
