name: Deploy to Production

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to BeGet server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: psp.realeasystudio.site
          username: abrobe14_psp
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/a/abrobe14/psp.realeasystudio.site/public_html
            bash deploy.sh
